# Site settings
title: Murcia Divergente
subtitle: Sociedad murciana que gira en torno a iniciativas solidarias, ecológicas y Do It Yourself/ (página en construcción)
email: murciadivergente@gmail.com
description: Un proyecto emergente para la cultura alternativa
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://murciadivergente.es/" # the base hostname & protocol for your site
author: Maria Montesinos
street_address: Calle paralela
city: Murcia 
state: Planeta Marte
zip_code: 
country: 
phone: 692 805 837

# Social settings
500px_url:
facebook_url: https://www.facebook.com/MurciaDivergente/
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/murcia_divergente/?hl=en
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
